### ISSUE TITLE
Possible Incompatablity issues? 

### ISSUE THREAD

**Issue by sferich888** [joaquimrocha/Leap-GNOME-Controller#2]
I built and installed the [Fedora RPM](https://github.com/atejeda/leap-fedora-rpm) for the Leap Motion using LeapDeveloperKit_release_linux_1.0.9+8391.tgz and Leap_Packages_1.0.9+8411_Linux.tgz

However I can not get this script to run on my Fedora 18 system.  I get the following Traceback:

```
Traceback (most recent call last):
  File "./leap-gnome-controller.py", line 218, in on_frame
    if frame.hands.empty:
  File "/home/eric/Repositories/Leap-GNOME-Controller/Leap.py", line 745, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, HandList, name)
  File "/home/eric/Repositories/Leap-GNOME-Controller/Leap.py", line 55, in _swig_getattr
    raise AttributeError(name)
AttributeError: empty
```

This seems to be caused by the following bit of code from the **Leap.py** scripted provided by the SDK.

```
def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)
```

**Comment by jacohend** [comment]
I get this same feedback on Ubuntu 12.10:

```
Traceback (most recent call last):
  File "./leap-gnome-controller.py", line 218, in on_frame
    if frame.hands.empty:
  File "/home/jacob/LeapDeveloperKit/LeapSDK/lib/Leap.py", line 745, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, HandList, name)
  File "/home/jacob/LeapDeveloperKit/LeapSDK/lib/Leap.py", line 55, in _swig_getattr
    raise AttributeError(name)
AttributeError: empty
```

The device will work with Visualizer and the other LeapMotion tools, but not with this.

**Comment by crvogt** [comment]
Anybody figure out this issue? Having the same problems myself

Running 12.04, and another person got it running with a different 12.04 computer, just don't know what he did.
